# Generated by Django 4.2.6 on 2023-11-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blog_name',
            field=models.CharField(default='dfdf', max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
