# Generated by Django 4.2.6 on 2023-11-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_russiantag_taggedwhatever_alter_post_tags'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-total_likes'], name='blog_app_po_total_l_37cf36_idx'),
        ),
    ]
