# Generated by Django 4.2.6 on 2023-11-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0008_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='moderator',
            field=models.BooleanField(default=False),
        ),
    ]
